### ISSUE TITLE
Missing .circ files

### ISSUE THREAD

**Issue by malustewart** [keithallatt/LogisimCPU#1]
First of all, let me tell you I'm really impressed with the amount of work done. Thank you for putting so much effort in producing detailed documentation and an IDE. 
When loading the Computer4Bit.circ file onto logisim-evolution, errors occur because the following files seem to be missing:
* EdgeDetector.circ
* BinaryToDecimalConverter.circ
* 7SegmentDecoder.circ

**Comment by keithallatt** [comment]
Hi! Thank you so much for your comment! I wasn't aware that my project used these files! But I'll add them in right away!

**Comment by keithallatt** [comment]
If the problem of missing files persists, make sure to re-import those *.circ files into the Computer4Bit.circ file. If this is still not possible please create a new issue.

**Comment by keithallatt** [comment]
Lines 101-103 Contain the import data for these, these use my local file paths (I don't know how to change that currently, other than re-creating those circuits) but a current fix will be to update those file paths until I release an update (or better yet someone can create a merge request!)
